media:
 - name: videos
    label: Videos
    input: src/media/videos
    output: /media/videos
    categories: [ video ]
  - name: images # Note: 'name' key is required here
    label: Images
    input: src/media/images
    output: /images
    categories: [ image ]

